# ==========================================
# \u672C\u756A\u74B0\u5883 (AWS RDS) \u7528 DB\u8A2D\u5B9A
# ==========================================
spring.datasource.url=jdbc:postgresql://money-manager-db.c9k8waoquikd.ap-northeast-1.rds.amazonaws.com:5432/money_manager
spring.datasource.username=postgres
spring.datasource.password=Eiji1104
spring.datasource.driver-class-name=org.postgresql.Driver

# \u672C\u756A\u306F\u7D76\u5BFE\u306B\u30C7\u30FC\u30BF\u3092\u6D88\u3057\u3061\u3083\u30C0\u30E1\u306A\u306E\u3067\u3001update\uFF08\u8FFD\u52A0\u30FB\u66F4\u65B0\u306E\u307F\uFF09\u306B\u3057\u3066\u304A\u304F
spring.jpa.hibernate.ddl-auto=update