# ==========================================
# \u30ED\u30FC\u30AB\u30EB\u74B0\u5883\u7528 DB\u8A2D\u5B9A
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5434/money_manager
spring.datasource.username=postgres
spring.datasource.password=Eiji1104
spring.datasource.driver-class-name=org.postgresql.Driver

# \u30ED\u30FC\u30AB\u30EB\u306F\u30C7\u30FC\u30BF\u304C\u6D88\u3048\u3066\u3082\u3044\u3044\u306E\u3067\u3001\u8D77\u52D5\u306E\u305F\u3073\u306B\u30C6\u30FC\u30D6\u30EB\u3092\u7DBA\u9E97\u306B\u4F5C\u308A\u76F4\u3059\uFF08\u89E3\u6C7A\u7B56A\uFF09
spring.jpa.hibernate.ddl-auto=update